name: Basic Workflow

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello Step 1
        run: echo "Hello, World!"
      - name: Echo Greetings Step 2
        run: echo "Greetings!!!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed Step
        run: |
          echo "It will be success!"
          exit 0
      - name: Echo Goodbye
        run: echo "Goodbye, World!"